### ISSUE TITLE
Support `star.plot` when `planet=None`

### ISSUE THREAD

**Issue by rodluger** [bmorris3/fleck#2]
Currently, if the user doesn't provide a planet instance when calling `Star.plot()`, several errors are raised, such as 
```python
AttributeError: 'NoneType' object has no attribute 'a'
```
because the `planet` attribute is `None`. It might be useful to allow users interested in just visualizing the star to use the plotting functionality.

On a related note, some other optional keywords to [plot](https://fleck.readthedocs.io/en/latest/api/fleck.Star.html#fleck.Star.plot) default to `None` and lead to errors if left unspecified. These include the star's rotation period and the time, which should probably default to something like infinity and zero, respectively. Otherwise, I recommend you make them positional arguments.

**Comment by bmorris3** [comment]
Thanks for this bug report. I've fixed this up in b6466e03730cc68fa966b2be2ba94b1ae7ff1078, you can now do the following:

```python
import matplotlib.pyplot as plt
from fleck import Star
import astropy.units as u
import numpy as np

spot_contrast = 0.7
u_ld = [0.5079, 0.2239]

n_phases = 30
lons = [[60]] * u.deg
lats = [[10]] * u.deg
radii = np.array([[0.1]])
inc_stellar = 90 * u.deg
stars = Star(spot_contrast=spot_contrast, n_phases=n_phases, u_ld=u_ld,
             rotation_period=10)
stars.plot(lons, lats, radii, inc_stellar, time=0)
plt.show()
```

![example1](https://user-images.githubusercontent.com/3497584/75627994-034ca780-5bcd-11ea-8bcb-cf0aa62fbd82.png)
